#!/bin/bash
# This is my startup script for running dwm on Debian with gdm3.
# When just using `startx` .xinitrc would be sufficient,
# but when you want to run from GDM do this:
# * install this script to /usr/local/bin (or symlink it)
# * add the statusbar script to $HOME/bin
# * install dwm.desktop into /usr/share/xsessions

# make gpg-agent with ssh-support working under dwm
export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
# start compositing for transparency
xcompmgr &
# restore background image: call `feh --bg-fill <image>` first
~/.fehbg &
# run my statusbar script
$HOME/bin/statusbar &
# screen locker
xset dpms 180
xss-lock -- slock &
# start default terminal
#konsole &
terminator &
# finally run dwm
exec dwm

